### ISSUE TITLE
project documentation

### ISSUE THREAD

**Issue by Ameise-github** [named-entity/nltk4russian#3]
Приветствую Вас! Подскажите пожалуйста, есть ли документация описания функций, которые используются в проекте? Как понять как работать с проектом?

**Comment by maranqz** [comment]
Привет, я думаю туториал лежит в https://github.com/named-entity/nltk4russian/tree/master/tutorials. Чтобы его смотреть используй jupyter notebook. Самый простой способ через Anaconda.

**Comment by Ameise-github** [comment]
> Привет, я думаю туториал лежит в https://github.com/named-entity/nltk4russian/tree/master/tutorials. Чтобы его смотреть используй jupyter notebook. Самый простой способ через Anaconda.

**Comment by Ameise-github** [comment]
Спасибо! Я думала еще где есть

**Comment by maranqz** [comment]
Синтаксический разбор есть тут.
https://github.com/named-entity/nltk4russian/blob/master/scripts/syntax.py
Диплом по этой теме
https://nauchkor.ru/pubs/predstavlenie-sintaksicheskih-svyazey-v-lingvisticheskom-protsessore-nltk4russian-5a6f881e7966e12684eea029

**Comment by Ameise-github** [comment]
Большое спасибо! Буду разбираться

**Comment by Ameise-github** [comment]
Доброго времени суток! Подскажите пожалуйста, какой версии Python надо использовать для работы с библиотекой? А то я использую Python 3.7 и у меня ошибки с кодировкой

**Comment by maranqz** [comment]
Здравствуйте, я использую 3.7 через конду, ошибок не выдает.
В каком месте у вас ошибка?

**Comment by Ameise-github** [comment]
Делаю по руководству nltk4ru-ex.ipynb. Ругается при вызове sents = list(read_corpus_to_nltk(f))
Ошибка такая: UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 708: character maps to <undefined>

**Comment by maranqz** [comment]
Скорее возможно нужно задать encoding="utf-8", но я не проверял.
with open('../data/media1.tab',  encoding="utf-8") as f:
    sents = list(read_corpus_to_nltk(f))

**Comment by Ameise-github** [comment]
Спасибо! Помогло

**Comment by Ameise-github** [comment]
Подскажите пожалуйста, почему при выводе тега у меня не полное его описание? По свойствам не нашла чтоб расширить ввод
```
for w, tag in t.tag(['дом', 'который', 'построил', 'джек']):
    print(w, tag)
```
Вывод таков: 
дом NOUN 
который ADJF
построил VERB
джек NOUN

**Comment by maranqz** [comment]
Скорее всего type_="full" нужно задать PMContextTagger.

У вас возникают простые вопросы, которые можно решить самостоятельно.

**Comment by doostybraun** [comment]
> Привет, я думаю туториал лежит в https://github.com/named-entity/nltk4russian/tree/master/tutorials. Чтобы его смотреть используй jupyter notebook. Самый простой способ через Anaconda.

Можете помочь мне запустить проэкт, я не могу запустить даже то что в туториале. У меня py 3.8.5 , я запускаю в idle такие строки

from nltk4russian.tagger import PMContextTagger
from nltk4russian.util import read_corpus_to_nltk


with open('../data/media1.tab') as f:
    sents = list(read_corpus_to_nltk(f))

//Путь в open копирую из проводника(тут путь из туториала)

получаю одни ошибки такого рода 

Traceback (most recent call last):
  File "<pyshell#5>", line 2, in <module>
    sents = list(read_corpus_to_nltk(f))
  File "C:\Users\lisin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nltk4russian\util.py", line 22, in read_corpus_to_nltk
    for t in inc:
  File "C:\Users\lisin\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 708: character maps to <undefined>

ВСЕ НУЖНЫЕ БИБЛИОТЕКИ СКАЧАНЫ(NLTK + PYMORPH2 + словари)

**Comment by doostybraun** [comment]
Уже не актуально
